// flow-typed signature: 46f6e16318b6b1db952fc76d246227e2
// flow-typed version: <<STUB>>/gulp-dotenv_v^0.2.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-dotenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-dotenv/build/dotenv' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-dotenv/build/dotenv.js' {
  declare module.exports: $Exports<'gulp-dotenv/build/dotenv'>;
}
