// flow-typed signature: 5e952de35bc172870823938c4f5ea1f0
// flow-typed version: <<STUB>>/gulp-s3-upload_v^1.6.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-s3-upload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-s3-upload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-s3-upload/src/helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-s3-upload/index' {
  declare module.exports: $Exports<'gulp-s3-upload'>;
}
declare module 'gulp-s3-upload/index.js' {
  declare module.exports: $Exports<'gulp-s3-upload'>;
}
declare module 'gulp-s3-upload/src/helper.js' {
  declare module.exports: $Exports<'gulp-s3-upload/src/helper'>;
}
