// flow-typed signature: 8235cb4c304d6345ed42191d5f87c3f4
// flow-typed version: <<STUB>>/redux-beacon_v^1.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-beacon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-beacon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-beacon/dist/redux-beacon.umd' {
  declare module.exports: any;
}

declare module 'redux-beacon/dist/redux-beacon.umd.min' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/dist/logger.umd' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/dist/logger.umd.min' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/dist/offline-web.umd' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/dist/offline-web.umd.min' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/logger/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/logger/logger' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/offline-react-native/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/offline-react-native/offline-react-native' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/offline-web/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/extensions/offline-web/offline-web' {
  declare module.exports: any;
}

declare module 'redux-beacon/lib/create-events' {
  declare module.exports: any;
}

declare module 'redux-beacon/lib/create-meta-reducer' {
  declare module.exports: any;
}

declare module 'redux-beacon/lib/create-middleware' {
  declare module.exports: any;
}

declare module 'redux-beacon/lib/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/lib/register-events' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/extensions/logger/__tests__/logger.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/extensions/logger/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/extensions/logger/logger' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/extensions/offline-react-native/__tests__/offline-react-native.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/extensions/offline-react-native/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/extensions/offline-react-native/offline-react-native' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/extensions/offline-web/__tests__/offline-web.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/extensions/offline-web/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/extensions/offline-web/offline-web' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/main/__tests__/create-events.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/main/__tests__/integration.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/main/__tests__/main.types.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/main/__tests__/register-events.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/main/create-events' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/main/create-meta-reducer' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/main/create-middleware' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/main/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/main/register-events' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/amplitude/__tests__/amplitude.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/amplitude/__tests__/amplitude.types.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/amplitude/amplitude' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/amplitude/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/cordova-google-analytics/__tests__/cordova-google-analytics.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/cordova-google-analytics/cordova-google-analytics' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/cordova-google-analytics/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-analytics/__tests__/google-analytics.node-env.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-analytics/__tests__/google-analytics.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-analytics/__tests__/google-analytics.types.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-analytics/google-analytics' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-analytics/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-tag-manager/__tests__/google-tag-manager.node-env.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-tag-manager/__tests__/google-tag-manager.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-tag-manager/__tests__/google-tag-manager.types.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-tag-manager/google-tag-manager' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/google-tag-manager/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/react-native/google-analytics/__tests__/google-analytics.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/react-native/google-analytics/google-analytics' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/react-native/google-analytics/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/react-native/google-tag-manager/__tests__/google-tag-manager.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/react-native/google-tag-manager/google-tag-manager' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/react-native/google-tag-manager/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/react-native/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/segment/__tests__/segment.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/segment/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/targets/segment/segment' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/utils/__tests__/add-timestamp.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/utils/__tests__/ensure.test' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/utils/add-timestamp' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/utils/ensure' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/utils/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/src/utils/ts-types-tester' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/amplitude/amplitude' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/amplitude/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/cordova-google-analytics/cordova-google-analytics' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/cordova-google-analytics/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/dist/cordova-google-analytics.umd' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/dist/cordova-google-analytics.umd.min' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/dist/google-analytics.umd' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/dist/google-analytics.umd.min' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/dist/google-tag-manager.umd' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/dist/google-tag-manager.umd.min' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/dist/segment.umd' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/dist/segment.umd.min' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/google-analytics/google-analytics' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/google-analytics/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/google-tag-manager/google-tag-manager' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/google-tag-manager/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/react-native/google-analytics/google-analytics' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/react-native/google-analytics/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/react-native/google-tag-manager/google-tag-manager' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/react-native/google-tag-manager/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/react-native/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/segment/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/targets/segment/segment' {
  declare module.exports: any;
}

declare module 'redux-beacon/utils/add-timestamp' {
  declare module.exports: any;
}

declare module 'redux-beacon/utils/ensure' {
  declare module.exports: any;
}

declare module 'redux-beacon/utils/index' {
  declare module.exports: any;
}

declare module 'redux-beacon/utils/ts-types-tester' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-beacon/dist/redux-beacon.umd.js' {
  declare module.exports: $Exports<'redux-beacon/dist/redux-beacon.umd'>;
}
declare module 'redux-beacon/dist/redux-beacon.umd.min.js' {
  declare module.exports: $Exports<'redux-beacon/dist/redux-beacon.umd.min'>;
}
declare module 'redux-beacon/extensions/dist/logger.umd.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/dist/logger.umd'>;
}
declare module 'redux-beacon/extensions/dist/logger.umd.min.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/dist/logger.umd.min'>;
}
declare module 'redux-beacon/extensions/dist/offline-web.umd.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/dist/offline-web.umd'>;
}
declare module 'redux-beacon/extensions/dist/offline-web.umd.min.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/dist/offline-web.umd.min'>;
}
declare module 'redux-beacon/extensions/logger/index.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/logger/index'>;
}
declare module 'redux-beacon/extensions/logger/logger.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/logger/logger'>;
}
declare module 'redux-beacon/extensions/offline-react-native/index.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/offline-react-native/index'>;
}
declare module 'redux-beacon/extensions/offline-react-native/offline-react-native.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/offline-react-native/offline-react-native'>;
}
declare module 'redux-beacon/extensions/offline-web/index.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/offline-web/index'>;
}
declare module 'redux-beacon/extensions/offline-web/offline-web.js' {
  declare module.exports: $Exports<'redux-beacon/extensions/offline-web/offline-web'>;
}
declare module 'redux-beacon/lib/create-events.js' {
  declare module.exports: $Exports<'redux-beacon/lib/create-events'>;
}
declare module 'redux-beacon/lib/create-meta-reducer.js' {
  declare module.exports: $Exports<'redux-beacon/lib/create-meta-reducer'>;
}
declare module 'redux-beacon/lib/create-middleware.js' {
  declare module.exports: $Exports<'redux-beacon/lib/create-middleware'>;
}
declare module 'redux-beacon/lib/index.js' {
  declare module.exports: $Exports<'redux-beacon/lib/index'>;
}
declare module 'redux-beacon/lib/register-events.js' {
  declare module.exports: $Exports<'redux-beacon/lib/register-events'>;
}
declare module 'redux-beacon/src/extensions/logger/__tests__/logger.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/extensions/logger/__tests__/logger.test'>;
}
declare module 'redux-beacon/src/extensions/logger/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/extensions/logger/index'>;
}
declare module 'redux-beacon/src/extensions/logger/logger.js' {
  declare module.exports: $Exports<'redux-beacon/src/extensions/logger/logger'>;
}
declare module 'redux-beacon/src/extensions/offline-react-native/__tests__/offline-react-native.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/extensions/offline-react-native/__tests__/offline-react-native.test'>;
}
declare module 'redux-beacon/src/extensions/offline-react-native/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/extensions/offline-react-native/index'>;
}
declare module 'redux-beacon/src/extensions/offline-react-native/offline-react-native.js' {
  declare module.exports: $Exports<'redux-beacon/src/extensions/offline-react-native/offline-react-native'>;
}
declare module 'redux-beacon/src/extensions/offline-web/__tests__/offline-web.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/extensions/offline-web/__tests__/offline-web.test'>;
}
declare module 'redux-beacon/src/extensions/offline-web/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/extensions/offline-web/index'>;
}
declare module 'redux-beacon/src/extensions/offline-web/offline-web.js' {
  declare module.exports: $Exports<'redux-beacon/src/extensions/offline-web/offline-web'>;
}
declare module 'redux-beacon/src/main/__tests__/create-events.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/main/__tests__/create-events.test'>;
}
declare module 'redux-beacon/src/main/__tests__/integration.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/main/__tests__/integration.test'>;
}
declare module 'redux-beacon/src/main/__tests__/main.types.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/main/__tests__/main.types.test'>;
}
declare module 'redux-beacon/src/main/__tests__/register-events.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/main/__tests__/register-events.test'>;
}
declare module 'redux-beacon/src/main/create-events.js' {
  declare module.exports: $Exports<'redux-beacon/src/main/create-events'>;
}
declare module 'redux-beacon/src/main/create-meta-reducer.js' {
  declare module.exports: $Exports<'redux-beacon/src/main/create-meta-reducer'>;
}
declare module 'redux-beacon/src/main/create-middleware.js' {
  declare module.exports: $Exports<'redux-beacon/src/main/create-middleware'>;
}
declare module 'redux-beacon/src/main/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/main/index'>;
}
declare module 'redux-beacon/src/main/register-events.js' {
  declare module.exports: $Exports<'redux-beacon/src/main/register-events'>;
}
declare module 'redux-beacon/src/targets/amplitude/__tests__/amplitude.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/amplitude/__tests__/amplitude.test'>;
}
declare module 'redux-beacon/src/targets/amplitude/__tests__/amplitude.types.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/amplitude/__tests__/amplitude.types.test'>;
}
declare module 'redux-beacon/src/targets/amplitude/amplitude.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/amplitude/amplitude'>;
}
declare module 'redux-beacon/src/targets/amplitude/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/amplitude/index'>;
}
declare module 'redux-beacon/src/targets/cordova-google-analytics/__tests__/cordova-google-analytics.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/cordova-google-analytics/__tests__/cordova-google-analytics.test'>;
}
declare module 'redux-beacon/src/targets/cordova-google-analytics/cordova-google-analytics.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/cordova-google-analytics/cordova-google-analytics'>;
}
declare module 'redux-beacon/src/targets/cordova-google-analytics/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/cordova-google-analytics/index'>;
}
declare module 'redux-beacon/src/targets/google-analytics/__tests__/google-analytics.node-env.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-analytics/__tests__/google-analytics.node-env.test'>;
}
declare module 'redux-beacon/src/targets/google-analytics/__tests__/google-analytics.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-analytics/__tests__/google-analytics.test'>;
}
declare module 'redux-beacon/src/targets/google-analytics/__tests__/google-analytics.types.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-analytics/__tests__/google-analytics.types.test'>;
}
declare module 'redux-beacon/src/targets/google-analytics/google-analytics.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-analytics/google-analytics'>;
}
declare module 'redux-beacon/src/targets/google-analytics/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-analytics/index'>;
}
declare module 'redux-beacon/src/targets/google-tag-manager/__tests__/google-tag-manager.node-env.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-tag-manager/__tests__/google-tag-manager.node-env.test'>;
}
declare module 'redux-beacon/src/targets/google-tag-manager/__tests__/google-tag-manager.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-tag-manager/__tests__/google-tag-manager.test'>;
}
declare module 'redux-beacon/src/targets/google-tag-manager/__tests__/google-tag-manager.types.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-tag-manager/__tests__/google-tag-manager.types.test'>;
}
declare module 'redux-beacon/src/targets/google-tag-manager/google-tag-manager.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-tag-manager/google-tag-manager'>;
}
declare module 'redux-beacon/src/targets/google-tag-manager/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/google-tag-manager/index'>;
}
declare module 'redux-beacon/src/targets/react-native/google-analytics/__tests__/google-analytics.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/react-native/google-analytics/__tests__/google-analytics.test'>;
}
declare module 'redux-beacon/src/targets/react-native/google-analytics/google-analytics.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/react-native/google-analytics/google-analytics'>;
}
declare module 'redux-beacon/src/targets/react-native/google-analytics/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/react-native/google-analytics/index'>;
}
declare module 'redux-beacon/src/targets/react-native/google-tag-manager/__tests__/google-tag-manager.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/react-native/google-tag-manager/__tests__/google-tag-manager.test'>;
}
declare module 'redux-beacon/src/targets/react-native/google-tag-manager/google-tag-manager.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/react-native/google-tag-manager/google-tag-manager'>;
}
declare module 'redux-beacon/src/targets/react-native/google-tag-manager/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/react-native/google-tag-manager/index'>;
}
declare module 'redux-beacon/src/targets/react-native/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/react-native/index'>;
}
declare module 'redux-beacon/src/targets/segment/__tests__/segment.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/segment/__tests__/segment.test'>;
}
declare module 'redux-beacon/src/targets/segment/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/segment/index'>;
}
declare module 'redux-beacon/src/targets/segment/segment.js' {
  declare module.exports: $Exports<'redux-beacon/src/targets/segment/segment'>;
}
declare module 'redux-beacon/src/utils/__tests__/add-timestamp.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/utils/__tests__/add-timestamp.test'>;
}
declare module 'redux-beacon/src/utils/__tests__/ensure.test.js' {
  declare module.exports: $Exports<'redux-beacon/src/utils/__tests__/ensure.test'>;
}
declare module 'redux-beacon/src/utils/add-timestamp.js' {
  declare module.exports: $Exports<'redux-beacon/src/utils/add-timestamp'>;
}
declare module 'redux-beacon/src/utils/ensure.js' {
  declare module.exports: $Exports<'redux-beacon/src/utils/ensure'>;
}
declare module 'redux-beacon/src/utils/index.js' {
  declare module.exports: $Exports<'redux-beacon/src/utils/index'>;
}
declare module 'redux-beacon/src/utils/ts-types-tester.js' {
  declare module.exports: $Exports<'redux-beacon/src/utils/ts-types-tester'>;
}
declare module 'redux-beacon/targets/amplitude/amplitude.js' {
  declare module.exports: $Exports<'redux-beacon/targets/amplitude/amplitude'>;
}
declare module 'redux-beacon/targets/amplitude/index.js' {
  declare module.exports: $Exports<'redux-beacon/targets/amplitude/index'>;
}
declare module 'redux-beacon/targets/cordova-google-analytics/cordova-google-analytics.js' {
  declare module.exports: $Exports<'redux-beacon/targets/cordova-google-analytics/cordova-google-analytics'>;
}
declare module 'redux-beacon/targets/cordova-google-analytics/index.js' {
  declare module.exports: $Exports<'redux-beacon/targets/cordova-google-analytics/index'>;
}
declare module 'redux-beacon/targets/dist/cordova-google-analytics.umd.js' {
  declare module.exports: $Exports<'redux-beacon/targets/dist/cordova-google-analytics.umd'>;
}
declare module 'redux-beacon/targets/dist/cordova-google-analytics.umd.min.js' {
  declare module.exports: $Exports<'redux-beacon/targets/dist/cordova-google-analytics.umd.min'>;
}
declare module 'redux-beacon/targets/dist/google-analytics.umd.js' {
  declare module.exports: $Exports<'redux-beacon/targets/dist/google-analytics.umd'>;
}
declare module 'redux-beacon/targets/dist/google-analytics.umd.min.js' {
  declare module.exports: $Exports<'redux-beacon/targets/dist/google-analytics.umd.min'>;
}
declare module 'redux-beacon/targets/dist/google-tag-manager.umd.js' {
  declare module.exports: $Exports<'redux-beacon/targets/dist/google-tag-manager.umd'>;
}
declare module 'redux-beacon/targets/dist/google-tag-manager.umd.min.js' {
  declare module.exports: $Exports<'redux-beacon/targets/dist/google-tag-manager.umd.min'>;
}
declare module 'redux-beacon/targets/dist/segment.umd.js' {
  declare module.exports: $Exports<'redux-beacon/targets/dist/segment.umd'>;
}
declare module 'redux-beacon/targets/dist/segment.umd.min.js' {
  declare module.exports: $Exports<'redux-beacon/targets/dist/segment.umd.min'>;
}
declare module 'redux-beacon/targets/google-analytics/google-analytics.js' {
  declare module.exports: $Exports<'redux-beacon/targets/google-analytics/google-analytics'>;
}
declare module 'redux-beacon/targets/google-analytics/index.js' {
  declare module.exports: $Exports<'redux-beacon/targets/google-analytics/index'>;
}
declare module 'redux-beacon/targets/google-tag-manager/google-tag-manager.js' {
  declare module.exports: $Exports<'redux-beacon/targets/google-tag-manager/google-tag-manager'>;
}
declare module 'redux-beacon/targets/google-tag-manager/index.js' {
  declare module.exports: $Exports<'redux-beacon/targets/google-tag-manager/index'>;
}
declare module 'redux-beacon/targets/react-native/google-analytics/google-analytics.js' {
  declare module.exports: $Exports<'redux-beacon/targets/react-native/google-analytics/google-analytics'>;
}
declare module 'redux-beacon/targets/react-native/google-analytics/index.js' {
  declare module.exports: $Exports<'redux-beacon/targets/react-native/google-analytics/index'>;
}
declare module 'redux-beacon/targets/react-native/google-tag-manager/google-tag-manager.js' {
  declare module.exports: $Exports<'redux-beacon/targets/react-native/google-tag-manager/google-tag-manager'>;
}
declare module 'redux-beacon/targets/react-native/google-tag-manager/index.js' {
  declare module.exports: $Exports<'redux-beacon/targets/react-native/google-tag-manager/index'>;
}
declare module 'redux-beacon/targets/react-native/index.js' {
  declare module.exports: $Exports<'redux-beacon/targets/react-native/index'>;
}
declare module 'redux-beacon/targets/segment/index.js' {
  declare module.exports: $Exports<'redux-beacon/targets/segment/index'>;
}
declare module 'redux-beacon/targets/segment/segment.js' {
  declare module.exports: $Exports<'redux-beacon/targets/segment/segment'>;
}
declare module 'redux-beacon/utils/add-timestamp.js' {
  declare module.exports: $Exports<'redux-beacon/utils/add-timestamp'>;
}
declare module 'redux-beacon/utils/ensure.js' {
  declare module.exports: $Exports<'redux-beacon/utils/ensure'>;
}
declare module 'redux-beacon/utils/index.js' {
  declare module.exports: $Exports<'redux-beacon/utils/index'>;
}
declare module 'redux-beacon/utils/ts-types-tester.js' {
  declare module.exports: $Exports<'redux-beacon/utils/ts-types-tester'>;
}
