// flow-typed signature: 2c3478003c8d41af93a9b659cca92a95
// flow-typed version: <<STUB>>/run-sequence_v^2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'run-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'run-sequence' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'run-sequence/index' {
  declare module.exports: $Exports<'run-sequence'>;
}
declare module 'run-sequence/index.js' {
  declare module.exports: $Exports<'run-sequence'>;
}
